<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '@@Активный@@',
    'Admin' => '@@Администратор@@',
    'Admins' => '@@Администраторы@@',
    'Are you sure you want to delete this item?' => '@@Вы уверенны, что хотите удалить этот элемент?@@',
    'Auth Key' => '@@@@',
    'Create' => '@@Создать@@',
    'Create Admin' => '@@Добавить Администратора@@',
    'Created At' => '@@Добавлено@@',
    'Delete' => '@@Удалить@@',
    'Email' => '@@@@',
    'Email Confirm Token' => '@@@@',
    'First Name' => '@@Имя@@',
    'ID' => '@@ID@@',
    'Inactive' => '@@Неактивный@@',
    'Last Name' => '@@Фамилия@@',
    'New Password' => '@@Новый пароль@@',
    'New Password Repeat' => '@@Повторить пароль@@',
    'Password Hash' => '@@@@',
    'Password Reset Expire' => '@@@@',
    'Password Reset Token' => '@@@@',
    'Reset' => '@@Сброс@@',
    'Role' => '@@Роль@@',
    'Search' => '@@Поиск@@',
    'Status' => '@@Статус@@',
    'Update' => '@@Редактировать@@',
    'Update Admin' => '@@Редактировать админа@@',
    'Updated At' => '@@Редактировано@@',
    'View Admin' => '@@Просмотр админа@@',
    'Dashboard' => 'Панель управления',
    'Incorrect username or password.' => 'Неправильный пароль',
    'Logout' => 'Выход',
    'Password' => 'Пароль',
    'Please Sign In' => 'Пожалуйста, войдите',
    'Remember Me' => 'Запомнить',
    'Sign in' => 'Вход',
    'Username' => 'Логин',
];
