<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Dashboard' => '',
    'Incorrect username or password.' => '',
    'Logout' => '',
    'Password' => '',
    'Please Sign In' => '',
    'Remember Me' => '',
    'Sign in' => '',
    'Username' => '',
    'Active' => '@@@@',
    'Admin' => '@@@@',
    'Admins' => '@@@@',
    'Are you sure you want to delete this item?' => '@@@@',
    'Auth Key' => '@@@@',
    'Create' => '@@@@',
    'Create Admin' => '@@@@',
    'Created At' => '@@@@',
    'Delete' => '@@@@',
    'Email' => '@@@@',
    'Email Confirm Token' => '@@@@',
    'First Name' => '@@@@',
    'ID' => '@@@@',
    'Inactive' => '@@@@',
    'Last Name' => '@@@@',
    'New Password' => '@@@@',
    'New Password Repeat' => '@@@@',
    'Password Hash' => '@@@@',
    'Password Reset Expire' => '@@@@',
    'Password Reset Token' => '@@@@',
    'Reset' => '@@@@',
    'Role' => '@@@@',
    'Search' => '@@@@',
    'Status' => '@@@@',
    'Update' => '@@@@',
    'Update Admin' => '@@@@',
    'Updated At' => '@@@@',
    'View Admin' => '@@@@',
];
